server:
  port: 8080

spring:
  profiles:
    active: local

---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        cache.use_second_level_cache: true
        cache.use_query_cache: false
        generate_statistics: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory