# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


### 1. 뿌리기 API
POST http://localhost:8080/money/sprinkling HTTP/1.1
Accept: *
Content-Type: application/json
X-USER-ID: fd151207-83b6-4014-84de-517e2c1a025a
X-ROOM-ID: 3a87933c-ea2a-4667-8cd2-dcd076c07eb4

{"receiverCount":2,"amount":10000}

### 2. 받기 API
###
###, "cea55869-f8bb-4b7b-b142-40c073d124a5"
#			, "5510eae0-cf4c-4488-a6e4-07e25ad030e0"
#			, "d61b76f0-5708-4ca6-8e20-c2897dbea1c8"
#			, "129ae99d-c21f-4020-bfa1-a2a71a4a1e8a")
###
PUT http://localhost:8080//money/sprinkling/receive/c82 HTTP/1.1
Accept: *
Content-Type: application/json
X-USER-ID: 5510eae0-cf4c-4488-a6e4-07e25ad030e0
X-ROOM-ID: 3a87933c-ea2a-4667-8cd2-dcd076c07eb4


### 3. 조회 API
GET http://localhost:8080/money/sprinkling/receive/1ff	 HTTP/1.1
Accept: *
Content-Type: application/json
X-USER-ID: fd151207-83b6-4014-84de-517e2c1a025a
X-ROOM-ID: 3a87933c-ea2a-4667-8cd2-dcd076c07eb4


######################### error ###########################
### 1. 뿌리기 API ( error ) - 4001
POST http://localhost:8080/money/sprinkling HTTP/1.1
Accept: *
Content-Type: application/json

{"userId":"fd151207-83b6-4014-84de-517e2c1a025a","messageRoomId":"3a87933c-ea2a-4667-8cd2-dcd076c07eb4","receiverCount":4,"amount":10000}

### 1. 뿌리기 API ( error ) - 4002
POST http://localhost:8080/money/sprinkling HTTP/1.1
Accept: *
Content-Type: application/json
X-USER-ID: fd151207-83b6-4014-84de-517e2c1a025a
X-ROOM-ID: 3a87933c-ea2a-4667-8cd2-dcd076c07eb4

{"amount":10000}

### 2. 받기 API (error) - 5000
PUT http://localhost:8080//money/sprinkling/receive/65e HTTP/1.1
Accept: *
Content-Type: application/json
X-USER-ID: 5510eae0-cf4c-4488-a6e4-07e25ad030e0
X-ROOM-ID: 3a87933c-ea2a-4667-8cd2-dcd076c07eb4


### 3. 조회 API ( error) - 이미 받기 완료
GET http://localhost:8080/money/sprinkling/receive/ea5 HTTP/1.1
Accept: *
Content-Type: application/json
X-USER-ID: 5510eae0-cf4c-4488-a6e4-07e25ad030e0
X-ROOM-ID: 3a87933c-ea2a-4667-8cd2-dcd076c07eb4

###

